#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness_user_db
#    username: postgres
#    password: Ayush@123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness_user_db
#    username: postgres
#    password: Ayush@123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: localhost








server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: Ayush@123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1